// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodTracker;

#nullable disable

namespace PeriodTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729105827_AddCycleHistoryView")]
    partial class AddCycleHistoryView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("PeriodTracker.AppState", b =>
                {
                    b.Property<int>("AppStatePropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("AppStatePropertyId");

                    b.ToTable("AppState");

                    b.HasData(
                        new
                        {
                            AppStatePropertyId = 1,
                            Value = "2"
                        },
                        new
                        {
                            AppStatePropertyId = 2,
                            Value = "2024-01-01T00:00:00"
                        });
                });

            modelBuilder.Entity("PeriodTracker.Cycle", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StartDate");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("PeriodTracker.CycleHistory", b =>
                {
                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("vCycleHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
