name: CI Build

on: [push, workflow_dispatch]

permissions:
    contents: read

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
    build-android:
        name: Android Build
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'microsoft'
                  java-version: '11'

            - name: Install MAUI Workloads
              run: |
                  dotnet workload install android --ignore-failed-sources
                  dotnet workload install maui --ignore-failed-sources

            - name: Create keystore
              shell: bash
              run: echo "${{ secrets.ANDROID_SIGNING_KEYSTORE }}" | base64 --decode > PeriodTracker.keystore

            # - name: Export signing key password
            #   env:
            #       ANDROID_SIGNING_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
            #   shell: bash
            #   run: echo "Hello from exporting singing key password!"

            # - name: Build MAUI Android
            #   run: dotnet build -f net8.0-android -c Release PeriodTracker.sln

            - name: Publish MAUI Android
              env:
                  IS_BUILD_CI_PUBLISH: true
              run: dotnet publish -f net8.0-android PeriodTracker.sln -p:AndriodSigningStorePass="${{ secrets.ANDROID_SIGNING_PASSWORD }}" -p:AndroidSigningKeyPass="${{ secrets.ANDROID_SIGNING_PASSWORD }}"
