name: CI Publish

on:
    release:
        types: [released]

permissions:
    contents: write

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
    build-android:
        name: Android Build
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'microsoft'
                  java-version: '11'

            - name: Install MAUI Workloads
              run: |
                  dotnet workload install android --ignore-failed-sources
                  dotnet workload install maui --ignore-failed-sources

            - name: Create keystore
              shell: bash
              run: echo "${{ secrets.ANDROID_SIGNING_KEYSTORE }}" | base64 --decode > PeriodTracker.keystore

            - name: Publish MAUI Android
              env:
                  IS_BUILD_CI_PUBLISH: true
              run: dotnet publish -f net8.0-android PeriodTracker.sln -p:AndroidSigningStorePass="${{ secrets.ANDROID_SIGNING_PASSWORD }}" -p:AndroidSigningKeyPass="${{ secrets.ANDROID_SIGNING_PASSWORD }}"

            - name: Save asset name
              id: save_asset_name
              shell: bash
              run: |
                cd publish
                echo "ASSET_NAME=$(ls -1 *.apk | head -n 1)" >> $GITHUB_OUTPUT

            - name: Upload asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: publish/${{ steps.save_asset_name.outputs.ASSET_NAME }}
                  asset_name: ${{ steps.save_asset_name.outputs.ASSET_NAME }}
                  asset_content_type: application/octet-stream
